name: nlp
channels:
  - defaults
dependencies:
  - python==3.9.0
  - numpy
  - tqdm
  - pandas
  - matplotlib
  - nltk
  - gensim
  - spacy
  - pytorch
  - torchinfo
  - transformers
  - datasets
  - termcolor
  - ipykernel